//! Check that public queries keep their attributes and compile without warnings.
#![deny(warnings, missing_docs)]

// Do not check docs for helpers generated by the input macro.
#[allow(missing_docs)]
mod input {
    /// An input with tracked methods.
    #[salsa::input]
    pub struct Input {}
}

pub use input::Input;

/// Attributes before the tracked macro stay on the public query.
#[must_use = "use the query result"]
#[deprecated(note = "old query")]
#[salsa::tracked(returns(copy))]
#[allow(unused_variables)]
pub fn before(_db: &dyn salsa::Database) -> u32 {
    let unused = 0;
    1
}

/// Attributes after the tracked macro stay on the public query.
#[salsa::tracked(returns(copy))]
#[must_use = "use the query result"]
#[deprecated(note = "old query")]
pub fn after(_db: &dyn salsa::Database) -> u32 {
    2
}

#[salsa::tracked]
impl Input {
    /// Attributes before the tracked macro stay on the public method.
    #[must_use = "use the method result"]
    #[deprecated(note = "old method")]
    #[salsa::tracked(returns(copy))]
    pub fn before(self, _db: &dyn salsa::Database) -> u32 {
        3
    }

    /// Attributes after the tracked macro stay on the public method.
    #[salsa::tracked(returns(copy))]
    #[must_use = "use the method result"]
    #[deprecated(note = "old method")]
    pub fn after(self, _db: &dyn salsa::Database) -> u32 {
        4
    }

    #[salsa::tracked(returns(copy))]
    #[cfg_attr(
        all(),
        doc = "Attributes in cfg_attr stay on the public associated function.",
        must_use = "use the associated function result",
        cfg_attr(all(), deprecated(note = "old associated function")),
        allow(unused_variables)
    )]
    pub fn associated(_db: &dyn salsa::Database) -> u32 {
        let unused = 0;
        5
    }
}

#[allow(deprecated)]
fn main() {
    let db = salsa::DatabaseImpl::new();
    let input = Input::new(&db);
    assert_eq!(before(&db), 1);
    assert_eq!(after(&db), 2);
    assert_eq!(input.before(&db), 3);
    assert_eq!(input.after(&db), 4);
    assert_eq!(Input::associated(&db), 5);
}
