use crate::key::DatabaseKeyIndex;
use rustc_hash::FxHashSet;

/// The maximum number of times we'll fixpoint-iterate before panicking.
///
/// Should only be relevant in case of a badly configured cycle recovery.
pub const MAX_ITERATIONS: u32 = 200;

/// Return value from a cycle recovery function.
#[derive(Debug)]
pub enum CycleRecoveryAction<T> {
    /// Iterate the cycle again to look for a fixpoint.
    Iterate,

    /// Cut off iteration and use the given result value for this query.
    Fallback(T),
}

/// Cycle recovery strategy: Is this query capable of recovering from
/// a cycle that results from executing the function? If so, how?
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum CycleRecoveryStrategy {
    /// Cannot recover from cycles: panic.
    ///
    /// This is the default.
    Panic,

    /// Recovers from cycles by fixpoint iterating and/or falling
    /// back to a sentinel value.
    ///
    /// This choice is computed by the query's `cycle_recovery`
    /// function and initial value.
    Fixpoint,
}

/// A "cycle head" is the query at which we encounter a cycle; that is, if A -> B -> C -> A, then A
/// would be the cycle head. It returns an "initial value" when the cycle is encountered (if
/// fixpoint iteration is enabled for that query), and then is responsible for re-iterating the
/// cycle until it converges. Any provisional value generated by any query in the cycle will track
/// the cycle head(s) (can be plural in case of nested cycles) representing the cycles it is part
/// of. This struct tracks these cycle heads.
#[derive(Clone, Debug, Default)]
pub(crate) struct CycleHeads(Option<Box<FxHashSet<DatabaseKeyIndex>>>);

impl CycleHeads {
    pub(crate) fn is_empty(&self) -> bool {
        // We ensure in `remove` and `extend` that we never have an empty hashset, we always use
        // None to signify empty.
        self.0.is_none()
    }

    pub(crate) fn contains(&self, value: &DatabaseKeyIndex) -> bool {
        self.0.as_ref().is_some_and(|heads| heads.contains(value))
    }

    pub(crate) fn remove(&mut self, value: &DatabaseKeyIndex) -> bool {
        if let Some(cycle_heads) = self.0.as_mut() {
            let found = cycle_heads.remove(value);
            if found && cycle_heads.is_empty() {
                self.0.take();
            }
            found
        } else {
            false
        }
    }
}

impl std::iter::Extend<DatabaseKeyIndex> for CycleHeads {
    fn extend<T: IntoIterator<Item = DatabaseKeyIndex>>(&mut self, iter: T) {
        let mut iter = iter.into_iter();
        if let Some(first) = iter.next() {
            let heads = self.0.get_or_insert(Box::new(FxHashSet::default()));
            heads.insert(first);
            heads.extend(iter)
        }
    }
}

impl std::iter::IntoIterator for CycleHeads {
    type Item = DatabaseKeyIndex;
    type IntoIter = std::collections::hash_set::IntoIter<Self::Item>;

    fn into_iter(self) -> Self::IntoIter {
        self.0.map(|heads| *heads).unwrap_or_default().into_iter()
    }
}

// This type can be removed once MSRV is 1.83+ and we have Default for hashset iterators.
pub(crate) struct CycleHeadsIter<'a>(
    Option<std::collections::hash_set::Iter<'a, DatabaseKeyIndex>>,
);

impl Iterator for CycleHeadsIter<'_> {
    type Item = DatabaseKeyIndex;

    fn next(&mut self) -> Option<Self::Item> {
        self.0.as_mut()?.next().copied()
    }

    fn last(self) -> Option<Self::Item> {
        self.0?.last().copied()
    }
}

impl std::iter::FusedIterator for CycleHeadsIter<'_> {}

impl<'a> std::iter::IntoIterator for &'a CycleHeads {
    type Item = DatabaseKeyIndex;
    type IntoIter = CycleHeadsIter<'a>;

    fn into_iter(self) -> Self::IntoIter {
        CycleHeadsIter(self.0.as_ref().map(|heads| heads.iter()))
    }
}

impl From<FxHashSet<DatabaseKeyIndex>> for CycleHeads {
    fn from(value: FxHashSet<DatabaseKeyIndex>) -> Self {
        Self(if value.is_empty() {
            None
        } else {
            Some(Box::new(value))
        })
    }
}

pub(crate) static EMPTY_CYCLE_HEADS: CycleHeads = CycleHeads(None);
