use crate::key::DatabaseKeyIndex;
use rustc_hash::FxHashSet;

/// The maximum number of times we'll fixpoint-iterate before panicking.
///
/// Should only be relevant in case of a badly configured cycle recovery.
pub const MAX_ITERATIONS: u32 = 200;

/// Return value from a cycle recovery function.
#[derive(Debug)]
pub enum CycleRecoveryAction<T> {
    /// Iterate the cycle again to look for a fixpoint.
    Iterate,

    /// Cut off iteration and use the given result value for this query.
    Fallback(T),
}

/// Cycle recovery strategy: Is this query capable of recovering from
/// a cycle that results from executing the function? If so, how?
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum CycleRecoveryStrategy {
    /// Cannot recover from cycles: panic.
    ///
    /// This is the default.
    Panic,

    /// Recovers from cycles by fixpoint iterating and/or falling
    /// back to a sentinel value.
    ///
    /// This choice is computed by the query's `cycle_recovery`
    /// function and initial value.
    Fixpoint,
}

/// A "cycle head" is the query at which we encounter a cycle; that is, if A -> B -> C -> A, then A
/// would be the cycle head. It returns an "initial value" when the cycle is encountered (if
/// fixpoint iteration is enabled for that query), and then is responsible for re-iterating the
/// cycle until it converges. Any provisional value generated by any query in the cycle will track
/// the cycle head(s) (can be plural in case of nested cycles) representing the cycles it is part
/// of. This struct tracks these cycle heads.
#[derive(Clone, Debug, Default)]
pub(crate) struct CycleHeads(Option<Box<FxHashSet<DatabaseKeyIndex>>>);

impl CycleHeads {
    pub(crate) fn is_empty(&self) -> bool {
        !self.0.as_ref().is_some_and(|heads| !heads.is_empty())
    }

    pub(crate) fn contains(&self, value: &DatabaseKeyIndex) -> bool {
        self.0.as_ref().is_some_and(|heads| heads.contains(value))
    }

    pub(crate) fn remove(&mut self, value: &DatabaseKeyIndex) -> bool {
        self.0.as_mut().is_some_and(|heads| heads.remove(value))
    }
}

impl std::iter::Extend<DatabaseKeyIndex> for CycleHeads {
    fn extend<T: IntoIterator<Item = DatabaseKeyIndex>>(&mut self, iter: T) {
        let heads = self.0.get_or_insert(Box::new(FxHashSet::default()));
        heads.extend(iter)
    }
}

impl std::iter::IntoIterator for CycleHeads {
    type Item = DatabaseKeyIndex;
    type IntoIter = std::collections::hash_set::IntoIter<Self::Item>;

    fn into_iter(self) -> Self::IntoIter {
        self.0.map(|heads| heads.into_iter()).unwrap_or_default()
    }
}

impl<'a> std::iter::IntoIterator for &'a CycleHeads {
    type Item = DatabaseKeyIndex;
    type IntoIter = std::iter::Copied<std::collections::hash_set::Iter<'a, DatabaseKeyIndex>>;

    fn into_iter(self) -> Self::IntoIter {
        self.0
            .as_ref()
            .map(|heads| heads.iter().copied())
            .unwrap_or_default()
    }
}

impl From<FxHashSet<DatabaseKeyIndex>> for CycleHeads {
    fn from(value: FxHashSet<DatabaseKeyIndex>) -> Self {
        Self(Some(Box::new(value)))
    }
}
